/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedRegisterRouteImport } from './routes/_unauthenticated/register'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedManageQuestionsRouteImport } from './routes/_authenticated/manage-questions'
import { Route as AuthenticatedCollabRouteImport } from './routes/_authenticated/collab'
import { Route as AuthenticatedUserUserIdRouteImport } from './routes/_authenticated/user.$userId'
import { Route as AuthenticatedAttemptAttemptIdRouteImport } from './routes/_authenticated/attempt.$attemptId'

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UnauthenticatedRegisterRoute = UnauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRouteRoute,
} as any)
const AuthenticatedManageQuestionsRoute =
  AuthenticatedManageQuestionsRouteImport.update({
    id: '/manage-questions',
    path: '/manage-questions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollabRoute = AuthenticatedCollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserUserIdRoute = AuthenticatedUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttemptAttemptIdRoute =
  AuthenticatedAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/collab': typeof AuthenticatedCollabRoute
  '/manage-questions': typeof AuthenticatedManageQuestionsRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/user/$userId': typeof AuthenticatedUserUserIdRoute
}
export interface FileRoutesByTo {
  '/collab': typeof AuthenticatedCollabRoute
  '/manage-questions': typeof AuthenticatedManageQuestionsRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/user/$userId': typeof AuthenticatedUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_authenticated/collab': typeof AuthenticatedCollabRoute
  '/_authenticated/manage-questions': typeof AuthenticatedManageQuestionsRoute
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/register': typeof UnauthenticatedRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/attempt/$attemptId': typeof AuthenticatedAttemptAttemptIdRoute
  '/_authenticated/user/$userId': typeof AuthenticatedUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/collab'
    | '/manage-questions'
    | '/login'
    | '/register'
    | '/'
    | '/attempt/$attemptId'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/collab'
    | '/manage-questions'
    | '/login'
    | '/register'
    | '/'
    | '/attempt/$attemptId'
    | '/user/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/collab'
    | '/_authenticated/manage-questions'
    | '/_unauthenticated/login'
    | '/_unauthenticated/register'
    | '/_authenticated/'
    | '/_authenticated/attempt/$attemptId'
    | '/_authenticated/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_unauthenticated/register': {
      id: '/_unauthenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthenticatedRegisterRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/manage-questions': {
      id: '/_authenticated/manage-questions'
      path: '/manage-questions'
      fullPath: '/manage-questions'
      preLoaderRoute: typeof AuthenticatedManageQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collab': {
      id: '/_authenticated/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof AuthenticatedCollabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/$userId': {
      id: '/_authenticated/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof AuthenticatedUserUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempt/$attemptId': {
      id: '/_authenticated/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/attempt/$attemptId'
      preLoaderRoute: typeof AuthenticatedAttemptAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollabRoute: typeof AuthenticatedCollabRoute
  AuthenticatedManageQuestionsRoute: typeof AuthenticatedManageQuestionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAttemptAttemptIdRoute: typeof AuthenticatedAttemptAttemptIdRoute
  AuthenticatedUserUserIdRoute: typeof AuthenticatedUserUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollabRoute: AuthenticatedCollabRoute,
  AuthenticatedManageQuestionsRoute: AuthenticatedManageQuestionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAttemptAttemptIdRoute: AuthenticatedAttemptAttemptIdRoute,
  AuthenticatedUserUserIdRoute: AuthenticatedUserUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedRegisterRoute: typeof UnauthenticatedRegisterRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedRegisterRoute: UnauthenticatedRegisterRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
