name: user-service → GCE VM

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/user-service/**'
      - '.github/workflows/deploy-userservice.yml'
  workflow_dispatch:

env:
  REGION: asia-southeast1
  PROJECT_ID: agile-charger-472814-j0
  REPO: my-docker-repo
  IMAGE: user-service
  CONTEXT_DIR: services/user-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

